export const LaptopFilter=[
    {
        filterType:"brand",
        filterOptions:[
        {label:"Acer",
         name:"acer"
        },
        {
           label: "Apple",
           name:"apple"
        },
        {
            label:"Asus",
            name:"asus"
        },
        {
            label:"Dell",
            name:"dell"
        },
        {
            label:"HP",
            name:"hp"
        },
        {
            label:"Lenovo",
            name:"lenovo"
        },
        {
            label:"MSI",
            name:"msi"
        }
        ]
    },
    {
        filterType:"price",
        filterOptions:[ 
       {
        label:"0-499",
        name:"priceTo499"
       },
       {
          label: "500-999",
          name:"priceTo999"
       },
       {
           label:"1000-1499",
           name:"priceTo1499"
       },
       {
           label:"1500-1999",
           name:"priceTo1999"
       },
       {
           label:"2000+",
           name:"price2000plus"
       }]
    }
]