export const Monitors=[{
    filterType:"brand",
    filterOptions:[
    {label:"Acer",
     name:"acer"
    },
    {
        label:"Asus",
        name:"asus"
    },
    {
        label:"Dell",
        name:"dell"
    },
    {
        label:"HP",
        name:"hp"
    },
    {
        label:"LG",
        name:"lg"
    },
    {
        label:"Philips",
        name:"philips"
    },
    {
        label:"Samsung",
        name:"samsung"
    }
    ]
}]